### ISSUE TITLE
Need to fix/update the RStudio project templates

### ISSUE THREAD

**Issue by jonmcalder** [lockedata/starters#102]
See https://github.com/lockedata/pRojects/tree/master/inst/rstudio/templates/project

This is obviously related to #71, but functionally separate. I'm happy to do this too, but will wait for feedback on #101 first.

**Comment by jonmcalder** [comment]
Like the shiny gadget, all of these project templates are outdated since they were based on older versions of the core functions which now have more/different arguments.

Example screenshots below.

<img width="1440" alt="screen shot 2019-01-03 at 19 39 43" src="https://user-images.githubusercontent.com/5055818/50652594-a4bb7780-0f8f-11e9-9171-ab32f08b0b6d.png">
<img width="1440" alt="screen shot 2019-01-03 at 19 39 56" src="https://user-images.githubusercontent.com/5055818/50652599-a84efe80-0f8f-11e9-9c03-7a7df99aa66b.png">

**Comment by maelle** [comment]
@stephlocke btw where were these templates documented/advertised? If we keep them, should there be a vignette about them or a note in the general vignette?

**Comment by stephlocke** [comment]
True, worth adding them to the readme
