### ISSUE TITLE
Add retries for repo deletion in tests

### ISSUE THREAD

**Issue by stephlocke** [lockedata/starters#108]
In the latest master build https://travis-ci.org/lockedata/starters/builds/477852270#L1133
>── 1. Error: createBasicProject() can create a GitHub repo (@test-AAA-createBasi
GitHub API error (404): 404 Not Found
  Not Found
1: gh::gh("DELETE /repos/:owner/:repo", owner = "chibimaelle", repo = "test") at testthat/test-AAA-createBasicProject.R:109

**Comment by maelle** [comment]
I think it was a random API failure because it now passes.

**Comment by stephlocke** [comment]
hmm, should we implementing retry logic to cope or would it be better to get retries into `gh`?

**Comment by maelle** [comment]
you mean in the tests or in the function?

**Comment by stephlocke** [comment]
in the function

**Comment by maelle** [comment]
Ok, will open an issue for that, but we might need retry for the deletion that happens in the tests.

**Comment by maelle** [comment]
In tests/test-AAA-createBasicProject.R

```r
gh::gh("DELETE /repos/:owner/:repo",
    owner = "chibimaelle", repo = "test"
  )
```
