### ISSUE TITLE
Automatically populate author info etc in DESCRIPTION

### ISSUE THREAD

**Issue by jonmcalder** [lockedata/starters#11]
Allow for author name, email etc to be set and then automatically populated in the DESCRIPTION when creating packages. These parameters can be included as function arguments as well, but should ideally be fetched by default so that they don't need to be specified repeatedly - I assume this is possible either by setting these parameters as options or via currying or something like that?

**Comment by stephlocke** [comment]
Yes, there's a bunch of devtools options we can set ... I'm not a huge fan of keeping env vars around so what about some sort of identity yaml file that can be chucked into relevant parameters?

**Comment by jonmcalder** [comment]
Yes I was thinking of a template identity file initially too. I think I'd also prefer that approach.

**Comment by jonmcalder** [comment]
Just came across this: https://github.com/gaborcsardi/conf

Very new of course, but could be useful here?

**Comment by maelle** [comment]
> I'm not a huge fan of keeping env vars around so what about some sort of identity yaml file that can be chucked into relevant parameters?

so @stephlocke you don't like the solution to keep stuff in .Rprofile? Cf http://usethis.r-lib.org/articles/articles/usethis-setup.html#store-default-values-for-description-fields-in-all-new-packages

**Comment by stephlocke** [comment]
Happy for whomai to be used

**Comment by maelle** [comment]
I actually don't like the `whoami` solution because the full name has to be split.

I'll be waiting a bit to see what happens over at https://github.com/r-lib/usethis/issues/474 &co

**Comment by maelle** [comment]
I think this should be a documentation issue instead, linking to usethis setup article.

**Comment by stephlocke** [comment]
Could we have a `starters::start_here()` function which takes through a lot of the usethis config etc?

**Comment by maelle** [comment]
That creates the template for Rprofile?

**Comment by stephlocke** [comment]
I'm thinking as many of the steps in that setup vignette as possible

**Comment by maelle** [comment]
The docs will tackle the `start_here()` function that includes a step about default DESCRIPTION values.
