### ISSUE TITLE
Remove the bestPractice argument from createPackageProject

### ISSUE THREAD

**Issue by maelle** [lockedata/starters#113]

**Comment by maelle** [comment]
Or at least make it have less effect.

**Comment by stephlocke** [comment]
If you can split these remaining things out then sure https://github.com/lockedata/starters/blob/master/R/createPackageProject.R#L89

**Comment by maelle** [comment]
What do you mean?

I'm not sure what would be added only when `bestPractice` is `TRUE`. 

* The code of conduct
* I'd be in favour of removing the licence stuff entirely because `usethis::create_package()` adds it if you store options in .Rprofile, and that's what we need to recommend because of #11 at least for now (I can't re-factor more at the moment).
* `usethis::use_package_doc()` 
* NEWS.md.

**Comment by stephlocke** [comment]
Once upon a time, many things were in the bestpractice section https://github.com/lockedata/starters/blob/e5cc9a867897cfff96a9bc09487fc6f439fc473b/R/createPackageProject.R#L21 but you've slowly but surely been moving things out of that section into their own toggleable parameters. 

I'd like every package to start with a CoC, NEWS, and a package vignette

**Comment by maelle** [comment]
So what would depend on bestPractice? Nothing and we remove it?

**Comment by stephlocke** [comment]
Yep - if you can move everything remaining out to relevant toggles / options then it's no longer needed

**Comment by maelle** [comment]
I'll remove it once we merge #111

**Comment by jonmcalder** [comment]
I'm working on #101 and have self-assigned #102 (though not started yet) which will both be impacted by this change, so I think I'll wait for you to get this done first @maelle?
