### ISSUE TITLE
What is checkpoint supposed to do?

### ISSUE THREAD

**Issue by maelle** [lockedata/starters#125]
Here's what we have now https://github.com/lockedata/starters/blob/4a3dd9f3720bb220a7c23abd3cffe82bae3871b4/R/utils.R#L27

@stephlocke you're a `checkpoint` user I think? 

I thought it did nothing but it seems it prevents further code from being run.

**Comment by maelle** [comment]
Now I run the setup for checkpoint/packrat at the very end so it doesn't prevent other things from happening but I'm not sure how to check the setup was correct.

**Comment by stephlocke** [comment]
It's doing some intiial setup of package caching by running checkpoint::checkpoint but it doesn't have to - we can create an R file somewhere that contains the checkpoint start and a link to the relevant vignette

**Comment by maelle** [comment]
Not sure I understand what that R file would be?

**Comment by maelle** [comment]
nowadays shouldn't one ditch packrat (and maybe even checkpoint) in favor of renv?

**Comment by stephlocke** [comment]
I haven't evaluated it yet, but I imagine so

**Comment by maelle** [comment]
Ok but deprecating "packrat" as an option is probably an excellent idea to save time. I'll see what I'll do reg checkpoint that I never really got.

**Comment by maelle** [comment]
checkpoint is no longer supported by starters.
