### ISSUE TITLE
Default earliest R version

### ISSUE THREAD

**Issue by stephlocke** [lockedata/starters#28]
Have some default value for earliest R version to go in  R DESCRIPTIONs

**Comment by maelle** [comment]
The current version on the user's system?

**Comment by maelle** [comment]
I'm wondering whether the current version on the user's system is a bit too strict, but I'm not sure I have a better idea.

**Comment by maelle** [comment]
See also discussion in https://github.com/ropensci/ozunconf18/issues/32

**Comment by maelle** [comment]
In particular https://community.rstudio.com/t/determining-which-version-of-r-to-depend-on/4396/14

**Comment by goldingn** [comment]
I like that 'Nick talking to himself out loud in public again' qualifies as discussion 😂

Glad to see others are interested in this too!

**Comment by maelle** [comment]
Also follow https://github.com/hadley/r-pkgs/issues/448

**Comment by stephlocke** [comment]
Ditch the dep then :)

**Comment by maelle** [comment]
You mean closing this issue, right?
