### ISSUE TITLE
Add name validation

### ISSUE THREAD

**Issue by stephlocke** [lockedata/starters#38]
As we use package skeletons, names folks can use are subject to R package naming rules. This causes bad user errors right now e.g. #36 and we should add some validation and documentation around the rules.

https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file

**Comment by maelle** [comment]
I'm wondering whether the availability should be relaxed when the project isn't a package.

**Comment by sgetalbo** [comment]
Hey @maelle - The previous work from archetana looks really good - can you let me know what more you think should be done here to improve it further?
