### ISSUE TITLE
Analysis: Add production scripts

### ISSUE THREAD

**Issue by stephlocke** [lockedata/starters#5]
For the skeleton docs (#2), have a script that produces them and sends to gh-pages branch or docs/ 

This could then be added to .travis.yml

**Comment by maelle** [comment]
cf https://github.com/ropenscilabs/tic -- `pRojects` could use it and https://github.com/ropenscilabs/travis

**Comment by maelle** [comment]
why not have the reports of analysis projects as vignettes, this way one would "just" need to run

```r
usethis::use_pkgdown()
travis::use_tic()
```

**Comment by stephlocke** [comment]
Typically analysis projects don't want a website output - they need word/pdf/notebooks etc

**Comment by maelle** [comment]
So what we need is some `use_tic()` wrapper that builds stuff from folder ??? (which one) and sends the output to gh-pages as you say.

I also wonder what would be in folder ???, e.g. only Rmd for html output?

**Comment by stephlocke** [comment]
build from analysis, render to outputs, deploy all outputs to separate presentation branch

**Comment by maelle** [comment]
yes but only Rmd?

**Comment by maelle** [comment]
We'll need a test with docx output before closing this. PDF output cf #4

**Comment by maelle** [comment]
docx output worked well without tweaking anything https://maelle.github.io/lockedata.starters9/try2.docx so I think we're good.
