### ISSUE TITLE
Make snake case function names too

### ISSUE THREAD

**Issue by stephlocke** [lockedata/starters#58]
I went kind of old school with `createBasicProject()` - I feel like we could also offer `create_basic_project()` for people with aesthetic objections to the old school naming convention without breaking things substantially for any existing users of the package.

This should be doable with extra code at the bottom of the function R files like 

```r
#' @describeIn createBasicProject
create_basic_project = createBasicProject
```

**Comment by maelle** [comment]
Should we even drop the "_project()"?

**Comment by stephlocke** [comment]
nah, let's leave project in for completeness of what the intent is

**Comment by sgetalbo** [comment]
If all is okay with the PR, should the readme also be updated to include the new functions?
