### ISSUE TITLE
Need better checks before 'cleaning up' after an error

### ISSUE THREAD

**Issue by jonmcalder** [lockedata/starters#92]
The call to `unlink()` with `recursive = TRUE` is very dangerous without some more checks in place. 
https://github.com/lockedata/pRojects/blob/f4b6d1f1c3521807ac8a778b5ce4c8cd7ee90315/R/createBasicProject.R#L115-L121

For example, since there is currently no explicit check for the presence of the `name` argument, one can call `createBasicProject()` and then upon any error or cancellation everything in the working directory (or whatever folder was specified) will be deleted 😿

**Comment by maelle** [comment]
:scream: interested in implementing this @jonmcalder

**Comment by maelle** [comment]
What other checks should take place now that #91 is fixed?

Or is it generally a bad idea to try and clean up?

**Comment by maelle** [comment]
Keeping this open in case we think of other criteria to use.

**Comment by jonmcalder** [comment]
Adding this here since #91 was already closed.

I think we also need an explicit length check on `name`, since `name = ''` will elude both `missing()` and `is.character()`. This is an edge case for sure, but a fairly easy trap to fall into when using the pRojects shiny gadget which results in the catastrophe 😿outlined above (the recursive nuking of one's entire working directory).

<img width="712" alt="screen shot 2018-12-27 at 16 57 06" src="https://user-images.githubusercontent.com/5055818/50484482-5a6b5100-09f9-11e9-8b15-9d22f0e12b11.png">

I'll submit a PR to address this.

**Comment by maelle** [comment]
did you experience any new catastrophe @jonmcalder?

**Comment by jonmcalder** [comment]
No I haven't noticed anything else, but I must confess I haven't really been using `starters` much in the past year 😱

**Comment by maelle** [comment]
Np, I was wondering whether it was ok to close this.

**Comment by jonmcalder** [comment]
Yes I think so - it's been long enough. We can re-open (or create a new issue) if we discover something else.

**Comment by maelle** [comment]
I hope we won't! :grin:
